### PR TITLE
test: api tests do not make the build fail, though they should

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Comment by ret2libc** [comment]
@radare as written on Telegram, there's a bug in the sdb_array_add_num api, so this is probably going to be red.

**Comment by radare** [comment]
why not fix the bug before making this change?

**Comment by ret2libc** [comment]
Sorry, i'm not that much into sdb neither that interested in it :( We can things as they were if you prefer.

**Comment by radare** [comment]
should be good to merge now, please rebase

**Pull request merged**
