### PR TITLE
Added array sorting functions #59

### PR DESCRIPTION
**Pull request by karel-**
didn't know alvarofe was already implementing this. but since this is a lot faster without sdb_array_get and sdb_array_set, maybe it's of use.

https://gist.github.com/karel-/74e671e91b09fb8e3f03#file-gistfile1-txt

### CODE REVIEW

**Comment by radare** [comment]
Cool! those new APIs seems interesting to have, can you please add the array_add_sorted and array_add_num_sorted() functions too?

Also, see the comments in the code style.

**Comment by radare** [comment]
Can you split that pullreq into two different ones?

First with the addition of sdb_get_len() and optimizing the places where sdb_get()+strlen() is used

Second, with the array sorting apis

**Comment by radare** [comment]
See `sdb_uncat` for example

**Comment by radare** [comment]
I think sdb_uncat is the only function that benefits from sdb_get_len(). but there are other places which are not yet using sdb_const_get_len() like in ` sdb_json_set` with the `js` variable

**Comment by karel-** [comment]
Splitting the pull request.

**Pull request closed without merging**
